### ISSUE TITLE
Move from flow to Typescript

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2052]
### Tasks list
- [x] rename files from .js to .ts
- [x] rename e2e files from .js to .ts
- [x] remove flow plugins from babel config
- [x] remove flow babel plugins from package.json dependencies
- [x] add ts plugins to babel
- [x] create tsconfig file
- [x] configure babel to work with ts
- [x] tests need to be configured to let Babel/register be aware of .ts extension.
- [x] add ts coverage script
- [ ] add ts coverage mininal rate for CI
- [x] remove flow from all npm scripts
- [ ] eslint needs to be set with typescript rules/plugins. :white_check_mark: :x:
- [x] remove flow eslint plugins from package.json dependencies
- [x] prettier needs to be changed to work with typescript. :white_check_mark: :x:
- [x] remove @flow annotations 
- [x] remove all $FlowFixMe 
- [x] configure a new task for the CI to run "tsc" for type checking. 
- [x] configure tsc to run only on a set of files that are clean.
- [ ] try to clean as much as possible typescript errors.
- [x] improve eslint-prettier-ts integration (eslint-prettier support old ts version only) - check how it affects lint-staged as well
- [x] make sure lint is green
- [x] make sure all unit-tests are passed.
- [x] make sure all e2e-tests are passed.

**Comment by davidfirst** [comment]
`configure tsc to run only on a set of files that are clean.` => can't be done with tsc. instead, I auto-added `@ts-ignore` above all ~1,700 errors.
`remove all $FlowFixMe` => done when `$FlowFixMe` was the whole line, otherwise, left.

**Comment by GiladShoham** [comment]
@davidfirst 
> The culprit was actually the prettier-eslint-cli not prettier-eslint. (it's confusing because you run "prettier-eslint", but in fact, the cli package is the one who starts the process

So can we mark this as checked? `improve eslint-prettier-ts integration (eslint-prettier support old ts version only) - check how it affects lint-staged as well`

**Comment by davidfirst** [comment]
@GiladShoham , yes, I checked it now.
