### ISSUE TITLE
interactive-project-setup

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2213]
# interactive-project-setup

The process of initializing a new Bit workspace should represent better the various workflow
features a developer should configure to their project.

## General changes
* rename `--interactive` flag to `--setup`

## What it should do

- define compiler
- define basic overrides (react/angular/styled-components/typescript...)
- define package manager

### Select project type

Bit should try and detect the project type (by reading the `package.json`).

```sh
[React/Vue/Angular/Node] project type detected.
- proceed
- select different framework
```

When Bit was not able to auto-detect (or user chose "select different"):

```sh
Select project framework
- React
- Vue
- Angular
- Node
- Abort
```

### Ask user to select project typing infra

first we should try to auto-detect

```sh
TypeScript/Flow configuration detected.
- proceed
- select different...
```

```sh
Select typing ?:
- TypeScript
- Flow
- None
```

### Define project styling

again, autodetect... need to see how viable it is

```sh
Emotion/StyledComponents styling detected.
- Proceed
- Select different styling framework
```

```sh
Select styling framework
- StyledComponents
- Emotion
- CSS modules (SCSS, SASS)
- CSS
- None
```

### Set package manager

```
What is your package manager?
- npm
- yarn
```

### configuration location

```sh
Where to place Bit's configuration:
- In dedicated config file
- In package.json
```

### In case there's already init-ed workspace

```sh
"target workspace <workspace location> already exists. pick an action:
- overwrite
- merge (not at the moment)
- cancel
```

### post interactive

- print the config file location
- print the actual values
- hint for next steps? link to somewhere in the docs?

## questions order

react -> types (plain / ts) (we should add react-flow compiler) -> styles  
angular -> styles 
Vue -> types (plain / ts / flow) -> styles
Node -> types (plain / ts / flow) -> styles

## auto detect rules
```js
const frameworkRules = {
  rules: [
    { name: 'react', packages: ['react', 'react-dom']},
    { name: 'angular', packages: ['@angular/core', '@angular/common']},
    { name: 'vue', packages: ['vue']}
  ],
  default: 'node'
}

const typeSystemRules = {
  rules: [
    { name: 'typescript', packages: ['typescript', '@babel/preset-typescript']},
    { name: 'flow', packages: ['@babel/preset-flow']}
  ],
  default: 'plain'
}

const stylingFrameworkRules = {
  rules: [
    { name: 'styled-components', packages: ['styled-components', 'babel-plugin-styled-components', 'typescript-plugin-styled-components', 'stylelint-config-styled-components']},
    { name: 'emotion', packages: ['emotion', '@emotion/core', 'babel-plugin-emotion']},
    { name: 'sass', packages: ['sass', 'sass-loader', 'node-sass', 'rollup-plugin-sass']},
    { name: 'scss', packages: ['rollup-plugin-scss']},
    { name: 'less', packages: ['less', 'less-loader']}
  ],
  default: 'none'
}
```

## actual config for specific answers

```
const COMPILERS_MAPPING = {
  react: {
    plain: 'bit.envs/compilers/react',
    typescript: 'bit.envs/compilers/react-typescript'
  },
  node: {
    plain: 'bit.envs/compilers/babel',
    flow: 'bit.envs/compilers/flow',
    typescript: 'bit.envs/compilers/typescript'
  },
  vue: {
    plain: 'bit.envs/compilers/vue',
    flow: 'bit.envs/compilers/vue',
    typescript: 'bit.envs/compilers/vue'
  },
  angular: {
    plain: 'not relevant',
    flow: 'not relevant',
    typescript: 'bit.envs/compilers/angular'
  }
};

const OVERRIDES_MAPPING = {
  react: {
    dependencies: {
      react: '-',
      'react-dom': '-'
    },
    peerDependencies: {
      react: '^16.9.0',
      'react-dom': '^16.9.0'
    },
    typescript: {
      devDependencies: {
        '@types/node': '+',
        '@types/react': '+',
        '@types/react-dom': '+'
      }
    }
  },
  angular: {
    dependencies: {
      '@angular/core': '-',
      '@angular/common': '-'
    },
    devDependencies: {
      '@types/node': '+'
    },
    peerDependencies: {
      '@angular/core': '>=8.0.0',
      '@angular/common': '>=8.0.0'
    }
  },
  vue: {
    typescript: {
      devDependencies: {
        '@types/node': '+'
      }
    }
  },
  node: {
    typescript: {
      devDependencies: {
        '@types/node': '+'
      }
    }
  },
  'styled-components': {
    react: {
      dependencies: {
        'styled-components': '-'
      },
      peerDependencies: {
        'styled-components': '+'
      },
      typescript: {
        devDependencies: {
          '@types/styled-components': '+'
        }
      }
    },
    vue: {
      dependencies: {
        'vue-styled-components': '-'
      },
      peerDependencies: {
        'vue-styled-components': '+'
      }
    },
    angular: {
      dependencies: {
        'styled-components': '-'
      },
      peerDependencies: {
        'styled-components': '+'
      },
      devDependencies: {
        '@types/node': '+',
        '@types/styled-components': '+'
      }
    },
    node: {
      dependencies: {
        'styled-components': '-'
      },
      peerDependencies: {
        'styled-components': '+'
      },
      typescript: {
        devDependencies: {
          '@types/node': '+',
          '@types/styled-components': '+'
        }
      }
    }
  },
  emotion: {
    dependencies: {
      emotion: '-',
      '@emotion/core': '-'
    },
    peerDependencies: {
      emotion: '+',
      '@emotion/core': '+'
    }
  }
};
```
## tasks list
- [x] rename `interactive` flag 
- [x] detect is workspace initialized
- [x] detect workspace metadata
- [x] define compiler rules
- [x] define overrides rules
- [x] match rules by workspace metadata
- [ ] support provide overrides rules to init api
- [ ] support override initalized workspace
- [ ] output the workspace config location
- [ ] output workspace config
- [ ] unit tests
- [ ] e2e tests

**Comment by GiladShoham** [comment]
progress is under the following branch - https://github.com/teambit/bit/tree/feature/new-init-interactive

**Comment by itaymendel** [comment]
need to rethink for v15
closing this one
