### ISSUE TITLE
Harmony - a new extension system engine

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2280]
WIP
This issue describes a major change of the bit internals and API called harmony.
Harmony is an extension system that builds and executes on a dependency graph of extensions through dependency injection (to expose API).

## Base extensions included as part of the first phase:
- [ ] bit
- [ ] build
- [x] capsule
- [x] cli
- [ ] component
- [ ] component-resolver
- [ ] composer
- [ ] dependency-resolver
- [ ] git
- [ ] graph
- [x] paper
- [ ] react
- [x] scope
- [x] watch
- [x] workspace
- [ ] bit new
- [x] bit create

## Missing stuff to merge it: 
- [ ] expose all core extensions from the API file
- [ ] make sure working against ssh server is working @GiladShoham  
- [x] [store extensions config upon tag](https://github.com/teambit/bit/issues/2295) @GiladShoham
- [ ] [new components config](https://github.com/teambit/bit/issues/2456)
- [ ] [extensions loading process](https://github.com/teambit/bit/issues/2455)
- [x] rethinkg about extension config/data storeing format @GiladShoham @ranm8 @davidfirst 
- [ ] [import component with extensions defined](https://github.com/teambit/bit/issues/2320) @GiladShoham 
- [x] make sure the docs generator is working
- [x] do not write dists files to workspace 
- [x] generate absolute links to capsules @davidfirst 
- [ ] JSON schema for bit json @ranm8 
- [ ] [Extension store](https://github.com/teambit/bit/issues/2295) @GiladShoham
- [ ] Load dependency graph correctly @GiladShoham
- [x] [Make extensions work as a dependency](https://github.com/teambit/bit/issues/2295) (import them as part of the component) @GiladShoham
- [ ] backward compatibility validation
   - [ ] bitmap
   - [ ] bit.json
   - [ ] objects
- [ ] build api @qballer 
   - [ ] change package.json
   - [ ] save dists
   - [ ] update deps
- [ ] test api @qballer 
   - [ ] save test results
   - [ ] unified experience 
- [ ] accept configuration for path of built capsules @davidfirst 
- [ ] change BitId string to BitId objects @davidfirst 
- [ ] support legacy hooks (pre-tag / post/pre import etc)
- [x] make sure analytics for new commands is working  
- [ ] show extensions in bit show 
- [x] make sure bit --help shows new commands - #2604 
- [ ] change bluebird debug config back to be env variable in app.ts 
- [ ] support node 8. change CircleCI yml to node 8.
- [ ] set npm as the default package manager
- [ ] [review bit help](https://github.com/teambit/bit/issues/2603)

## bugs to fix before merge:
- [x] Converting circular structure to JSON @qballer 
- [ ] Make sure Harmony throws an exception when circular dependencies exist in the graph @GiladShoham 
- [ ] capsules should be created successfully when the components have cyclic dependencies (enable cyclic-dependencies.e2e.2.ts tests). @imsnif 

## tests to write before the merge
- [x] [persist extension config](https://github.com/teambit/bit/issues/2321)
- [x] make sure windows tests are green - #2585 #2565  #2599 

## Docs
- [ ] Review every core extension and make sure it has 
  - [ ] readme file
  - [ ] jsdocs for each public function at least

**Comment by itaymendel** [comment]
irrelevant
